import Head from 'next/head'
import {PostCard,PostWidget,Categories,Header} from "../components/"
import { getPosts } from '../services'




export default function Home({posts}) {

  return (
    <div>
      <Head>
        <title>Kadın Hastalıkları</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      {posts.map((post,index)=>(
  post.node.isFeaturedOne ? [] : <PostCard post={post} key={index} />
        
      ))}

      {/* <PostWidget/>
      <Categories/> */}
    </div>
    </div>
  )
}

//fetching data with nextx js
export async function getStaticProps(){
  const posts= (await getPosts()) || [];
  return{
    props: {posts}
  }
}