import Head from "next/head";
import { useState } from "react";
import {
  PostCards,
  FeaturedOne,
  Serie,
  Header,
  FeaturedBanner,
  EditorsPick,
  CommercialArea,
  Footer,
} from "../components/";
import {
  getPosts,
  getSeries,
  getFeaturedBannerPost,
  getFeaturedOnePost,
  getEditorsPick,
  getCategories
} from "../services";
import styles from "../styles/Home.module.css";

export default function Home({
  posts,
  series,
  featuredBannerPost,
  featuredOnePost,
  editorPicks,
  categories
})
{



  return (
    <div >
      <Head>
        <title>Kadın Hastalıkları</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header categories={categories} featuredOnePost={featuredOnePost}  />

      <FeaturedBanner featuredBannerPost={featuredBannerPost} />

      <PostCards posts={posts} />

      <Serie series={series} />

      <FeaturedOne featuredOnePost={featuredOnePost} />

      <CommercialArea />

      <EditorsPick editorPicks={editorPicks} />

      <Footer categories={categories} />
    </div>
  );
}

//fetching data with nextx js
export async function getStaticProps() {
  const posts = (await getPosts()) || [];
  const series = (await getSeries()) || [];
  const featuredBannerPost = (await getFeaturedBannerPost()) || [];
  const featuredOnePost = (await getFeaturedOnePost()) || [];
  const editorPicks = (await getEditorsPick()) || [];
  const categories=  (await getCategories()) || []; 

  return {
    props: {
      posts: posts,
      series: series,
      featuredBannerPost: featuredBannerPost,
      featuredOnePost: featuredOnePost,
      editorPicks: editorPicks,
      categories:categories
    },
  };
}
